### ISSUE TITLE
Build clojure-lsp with clj-nix

### ISSUE THREAD

**Issue by jlesquembre** [jlesquembre/clj-nix#1]
It should help with https://github.com/clojure-lsp/clojure-lsp/pull/604

**Comment by ericdallo** [comment]
@jlesquembre I'm giving it a try and something I missed from docs is a way to `nix flake new` for a existing non nix repo, like clojure-lsp. Maybe we could add to docs how to do that, I received this error:
```
error: refusing to overwrite existing file '/home/greg/dev/clojure-lsp/deps.edn'
``` 

And manually generate to another folder and copied that deps.edn

**Comment by ericdallo** [comment]
Yeah, I just found that issue right now 😅 
NP, please let me know and thank you !

**Comment by jlesquembre** [comment]
Finally, I was able to build clojure-lsp :)

https://github.com/jlesquembre/clojure-lsp/tree/flake

```shell
nix run github:jlesquembre/clojure-lsp/flake#cli -- --version
```

**Comment by jlesquembre** [comment]
https://github.com/clojure-lsp/clojure-lsp/pull/999 :tada:
