### ISSUE TITLE
hash mismatch for git dependency

### ISSUE THREAD

**Issue by sg-qwt** [jlesquembre/clj-nix#109]
```
error: hash mismatch in fixed-output derivation '/nix/store/n44189m4l4rpk4cm82j6hkg171y7d1zp-systemic-2c0be3a.drv':
         specified: sha256-ODwGyIdTB5HNwMyc0FEXFZ1AVWAGEz+ItDH4SGyrLGs=
            got:    sha256-pxbxFZirXL9CD37rhXUw/MMdxMZbLkVqfZIQXSpDqaI=
```

Hi,

I've got a git deps in deps.edn, and I've got hash mismatch from the generated deps-lock.json

```Clojure
{ :deps  {
         teknql/systemic {:git/sha "2c0be3a90884f998a61f2a8174cff3c5a15a30bf"
                          :git/url "https://github.com/teknql/systemic"}
      }
}
```

In that json, hash says sha256-ODwGyIdTB5HNwMyc0FEXFZ1AVWAGEz+ItDH4SGyrLGs=
But during build, hash got mismatch somehow, I've manually change the hash in deps-lock.json this case.

Best

**Comment by jlesquembre** [comment]
@sg-qwt I think we fixed it in #126 , let me know if it's fixed for you

**Comment by sg-qwt** [comment]
Yes, it is. Many thanks!

**Comment by JJ-Atkinson** [comment]
I think this is happening still with `https://github.com/nextjournal/clojure-mode`. I'll follow up with more details tomorrow most likely.
