### ISSUE TITLE
Support :exclusions in next branch

### ISSUE THREAD

**Issue by john-shaffer** [jlesquembre/clj-nix#11]
Some maven dependencies don't work with the clojure CLI, so I use `:exclusions` to ignore those. [bouncycastle/bctsp-jdk14](https://search.maven.org/artifact/bouncycastle/bctsp-jdk14/138/jar) is the main offender. It has a relocation marker rather than a jar, which `clojure.tools.deps` can't handle. The workaround is to exclude it and manually specify the new artifact names (under `org.bouncycastle`). This doesn't work with clj-nix/next.

With this deps.edn,
```
{:paths ["src"]
 :deps {net.sourceforge.tess4j/tess4j {:mvn/version "4.6.0"
                                       :exclusions [bouncycastle/bctsp-jdk14]}}}

```
running `nix run github:jlesquembre/clj-nix/next#deps-lock` produces:
```
Downloading: org/clojure/clojure/1.10.3/clojure-1.10.3.jar from central
Downloading: commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar from central
Execution error (ExceptionInfo) at clojure.tools.deps.alpha.extensions.maven/get-artifact (maven.clj:167).
Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)
```

It works fine with current `main` though.

**Comment by john-shaffer** [comment]
This is actually unnecessary for tess4j since 4.6.1, so the need for this may not be great. It should at least be documented, however.

**Comment by neshtea** [comment]
> I think there should at least be a warning that clj-nix is ignoring it

I don't think this will suffice.  It is necessary to do this quite often (at least I and people/projects I know of need to to this).  One regular use-case is to `:exclude` certain logging facades from you deps (i.e. `org.slf4j/slf4j-log4j12` and friends).

**Comment by jlesquembre** [comment]
Yep, it's a bug, it was working previously. Exclusions should be supported.
Thanks for reporting it, I'll fix it

**Comment by jlesquembre** [comment]
It should be fixed on main branch, I'll do some more test before closing the issue
