### ISSUE TITLE
checkPhase

### ISSUE THREAD

**Issue by Sohalt** [jlesquembre/clj-nix#12]
It would be nice to be able to use `checkPhase` to run unit tests, e.g. using `clojure -X:test` or some other test runner.
Maybe a general approach would be to pass all "unknown" attributes to `mkCljBin` through to `mkDerivation`. This is also done in a few other `mkDerivation` "wrappers", e.g. [mkshell](https://github.com/NixOS/nixpkgs/blob/b0c6c8c92b86b16cab9fad72bd836cc1d2aba8f8/pkgs/build-support/mkshell/default.nix#L21).

**Comment by jlesquembre** [comment]
Totally agree.
I'm not sure about the best way to do it, but it makes a lot of sense to provide a way to run the tests in the checkPhase.

**Comment by Sohalt** [comment]
What do you think about my suggestion to just pass the attributes to `mkDerviation`? That way I could write something like
```nix
mkCljBin {
  name = "foo";
  projectSrc = ./.;
  main-ns = "foo.main";
  checkPhase = "clj -X:test";
}
```

**Comment by jlesquembre** [comment]
@Sohalt I like it, probably I'll implement it that way :+1: 

But first I have to finish the work I'm doing in the `local-cache` branch, without those changes, specifying an alias at nix build time it's not going to work

**Comment by Sohalt** [comment]
Ah, I didn't know that. Thanks!

**Comment by jlesquembre** [comment]
Done, see an example here: https://github.com/jlesquembre/clj-nix#mkcljbin

Now you can do: 
```nix
mkCljBin {
  # ...
  doCheck = true;
  checkPhase = "clj -M:test";
}

```

**Comment by jlesquembre** [comment]
@Sohalt Thanks again for pointing me to the mkshell example :)
