### ISSUE TITLE
maven requires `https` but the lock file contains `http` URLs to maven (or: why use the map `maven-repos`?)

### ISSUE THREAD

**Issue by cresh** [jlesquembre/clj-nix#154]
We have one (rather old) dependency to [clojure-csv](https://github.com/davidsantiago/clojure-csv) in a project that we want to nixify with clj-nix. This dependency still lists `central` with a `http` URL in its `pom`:

```
...
  <repositories>
    <repository>
      <id>central</id>
      <url>http://repo1.maven.org/maven2/</url>
...
```

clj-nix collects maven dependencies in the `maven-repos` map from `id` to `url` starting from the standard repos:

```
(def standard-repos {"central" {:url "https://repo1.maven.org/maven2/"}
                     "clojars" {:url "https://repo.clojars.org/"}})
```

In our case, clj-nix overwrites the `https` URL for the key `"central"` with the `http` URL it found in the `clojure-csv.pom` file while collecting the dependencies in the `maven-repos` map, this happens in `cljnix.utils/get-maven-repos.

When clj-nix writes the lock file, it uses the `maven-repos` map to lookup the URL with `repo-name` (like `"central"`). For our project, all our `"central"` dependencies now want to be fetched from the no-longer-working `http` link:

```
error: builder for '/nix/store/7jw2mkaldzhb44g8r4x59pcc0rkrwp48-core.match-1.0.0.jar.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying http://repo1.maven.org/maven2/org/clojure/core.match/1.0.0/core.match-1.0.0.jar
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 501
       > error: cannot download core.match-1.0.0.jar from any mirror

       
> curl -L http://repo1.maven.org/maven2/org/clojure/core.match/1.0.0/core.match-1.0.0.jar
501 HTTPS Required.
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```

Why does clj-nix use the `maven-repos` map at all? Wouldn't it be more correct (and easier) to use the repositories that each dependency defines directly instead? If the map is needed, should clj-nix prefer `https` links? Do you know a quick solution to our problem?

**Comment by jlesquembre** [comment]
if the project is open source, could you provide a link?

**Comment by cresh** [comment]
Unfortunatelly, the project is not open source, but I can provide the content of the `deps.edn` file here that does cause `nix run github:jlesquembre/clj-nix#deps-lock` to put `http://` links into `deps-lock.json`:

```
{:deps {org.clojure/clojure            {:mvn/version "1.11.1"}
        org.clojure/tools.cli          {:mvn/version "1.0.194"}
        de.active-group/active-clojure {:mvn/version "0.42.0"}
        clojure-csv/clojure-csv        {:mvn/version "2.0.1"}
        clj-time/clj-time              {:mvn/version "0.15.2"}
        org.clojure/data.json          {:mvn/version "2.5.0"}
        org.clj-commons/clj-http-lite  {:mvn/version "1.0.13"}}

 :paths ["src" "resources" "classes"]

 :aliases {:uberjar {:extra-deps {uberdeps/uberdeps {:mvn/version "0.1.10"}}
                     :main-opts ["-m" "uberdeps.uberjar"]}}}
```

Hope this helps!

**Comment by jlesquembre** [comment]
thanks, #159 should fix it

We need the maven repo map because maven dependencies can define additional repositories (see https://github.com/jlesquembre/clj-nix/issues/98). 
But those should have lower priority according to https://maven.apache.org/guides/mini/guide-multiple-repositories.html#Repository_Order

**Comment by cresh** [comment]
Using

```
nix run github:jlesquembre/clj-nix/fix-mvn-repo-order#deps-lock
```

produces now a `deps-lock.json` that does not contain http links.

Great, thank you very much!
