### ISSUE TITLE
Adopt REUSE specification for licensing

### ISSUE THREAD

**Issue by seabass-labrax** [jlesquembre/clj-nix#2]
Greetings! It would be nice to have licensing and copyright information for this project in a form following the [REUSE](https://reuse.software/) specification. It's based on the principle of having the information as close to the data that it relates to as possible, which is especially advantageous when code is copied and pasted between projects. For instance, each file of Clojure source code would have a header comment like this:

```clojure
;; SPDX-License-Identifier: EPL-2.0
;; SPDX-FileCopyrightText: 2022 José Luis Lafuente <jl@lafuente.me>

(ns core
    ...
```

Furthermore, all the licences that the project is published under are stored as text files in a directory called `LICENSES`. When the number of licences increases due to code incorporated from other projects, or with a dual-licensing setup (for instance in the way that the Eclipse 2.0 licence has a Secondary Licenses provision), it's easier for automated licence scanning tools to find them with REUSE, compared to a single file containing multiple licence texts.

If you'd like to see an example of this for a full Clojure application, feel free to take a look at my project at <https://git.libregaming.org/LibreGaming/matchbot>. Oh, and you can have a [nice green badge](https://git.fsfe.org/reuse/reuse-ci/raw/branch/master/reuse-compliant.svg) in the README too :grinning:

Looking forward to hearing back from you on this!

**Comment by jlesquembre** [comment]
For now, this is not a priority for me.
