### ISSUE TITLE
Explicit support for multi-release jars

### ISSUE THREAD

**Issue by thenonameguy** [jlesquembre/clj-nix#20]
I have some dependencies like https://github.com/brettwooldridge/HikariCP that are distributed as multi-release jar files from Maven Central (generally clojure deps are source-based and avoid this problem.)
The `customJdk` function's `jdeps` step does not seem to not support this currently and fails on a missing `--multi-release <version>` flag.

[I started creating a branch](https://github.com/thenonameguy/clj-nix/tree/feat/multi-release-support) that allowed me to get into the module dependency resolution phase, but I seem to unable to get it resolved.

Have you had issues like this before?
Additionally, it would be great if the `mkCljBin` could operate on the output of a non `customJdk` output derivation, for cases where this kind of issue happens.

Thanks for all the hard work so far on this, looking forward to contributing!

**Comment by jlesquembre** [comment]
I didn't consider multi-release jars (well, I didn't know about it ;) )

I guess we could check if the uberjar generated by `mkCljBin` is a multi-release jar, and then add the `--multi-release <version>` option to the `jdeps` command. The `<version>` could be extracted from the jdk version we pass to `customJdk`. I'll try to add support for it.

> Additionally, it would be great if the `mkCljBin` could operate on the output of a non `customJdk` output derivation

Not sure what you mean, `mkCljBin` generates and uberjar, and a wrapper script to run that uberjar, something like `java -jar file.jar`. The `java` on that script is one the jdks provided by nixpkgs. It doesn't depend on the `customJdk` derivation
On the other hand, `customJdk` depends on the derivation generated by `mkCljBin`. Maybe am I missing something?

**Comment by jlesquembre** [comment]
My first try gives this error(running jdeps): 

`Exception in thread "main" java.lang.module.FindException: Module org.slf4j not found, required by com.zaxxer.hikari`

Looks related to this issue: https://github.com/brettwooldridge/HikariCP/issues/1746

@thenonameguy are you able to execute `jdeps` in a project with HikariCP?

**Comment by thenonameguy** [comment]
Thanks for the responses!
Sorry, still learning to wrangle Nix/Java modules in my head :) 
That seems to be the issue, yes:
```
jdeps --multi-release 9 /nix/store/g617cm4n47vw3hr7kam5cvjrlb1xim2s-meatico-DEV-lib/meatico-DEV.jar
Exception in thread "main" java.lang.module.FindException: Module org.slf4j not found, required by com.zaxxer.hikari
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
```
I did the `deps.edn` slf4j exclusion already, but I think that does not have an effect on the module metadata within the jar of HikariCP. :cry: 
I know it's not strictly related to this project, but it would be great to find a solution to this, maybe some classpath filtering in the clojure source of clj-nix?

**Comment by jlesquembre** [comment]
Let's try to get it working without nix, just with plain clj tools. I had a dummy project with HikariCP as a dependency, but I still get the same error. If I'm able to find a solution, I can do the same in clj-nix, or at least document how to solve the issue.

I also think that the issue is not related to clj-nix, but it'd be nice to find a solution for this, HikariCP is a dependency for many projects.

**Comment by thenonameguy** [comment]
FYI by downgrading to `3.4.3` as mentioned in the linked issue, allowed me to progress...
```
modified   backend/deps-lock.json
@@ -1463,14 +1463,14 @@
       "hash": "sha256-yFBR8vnXjMK0mOZfGbsdZJA3IRNNHmCiSRFbOMBZ2iQ="
     },
     {
-      "mvn-path": "com/zaxxer/HikariCP/5.0.1/HikariCP-5.0.1.jar",
+      "mvn-path": "com/zaxxer/HikariCP/3.4.3/HikariCP-3.4.3.jar",
       "mvn-repo": "https://repo1.maven.org/maven2/",
-      "hash": "sha256-JtSSOX5ndbQpZzeokZvwQEev5YJ/3SwItFV1lUNrOis="
+      "hash": "sha256-an6LNtplMRqEtZ1gP9gNY2upPBLR6dJuuHRfXHCM6vY="
     },
     {
-      "mvn-path": "com/zaxxer/HikariCP/5.0.1/HikariCP-5.0.1.pom",
+      "mvn-path": "com/zaxxer/HikariCP/3.4.3/HikariCP-3.4.3.pom",
       "mvn-repo": "https://repo1.maven.org/maven2/",
-      "hash": "sha256-xHNfXT/2ylsyI0Xofw3diA9XkNiLzle6/hqfn8eeAq4="
+      "hash": "sha256-usypzYocFORZRILUOR05TSDAHVnN2hmzNi0QvhBFdIc="
     },
     ```
Now getting:
```
Exception in thread "main" java.lang.module.FindException: Module com.fasterxml.jackson.annotation not found, required by com.fasterxml.jackson.databind
```
Onto the next one :)

**Comment by jlesquembre** [comment]
The issue is not in 3.4.3 because that version is not a multi-release jar. I hope we can find a proper solution for multi-release jars

**Comment by jlesquembre** [comment]
@thenonameguy I finally got a version working, with latest HikariCP version (5.0.1)

You have 2 options to create a custom jdk. One is to pass the `jdkModules` to `customJdk`, e.g.:

```nix
customJdk {
  cljDrv = self.packages."${system}".clj-tuto;
  jdkModules = "java.base,java.desktop,java.management,java.naming,java.sql,jdk.unsupported";
  locales = "en,es";
}
``` 

this way, `jdeps` is not called, since we provide the jdk modules.


The other alternative is to pass `multiRelease = true` to `customJdk`, e.g.:

```nix
customJdk {
  cljDrv = self.packages."${system}".clj-tuto;
  multiRelease = true; # Or a number, like 11 or 17
  locales = "en,es";
}
``` 
The multiRelease option is currently only in the [multirelease branch](https://github.com/jlesquembre/clj-nix/tree/multirelease)

I'm don't know why, but calling `jdeps --multi-release` with a version number fails, while calling it with the option `base` works. Setting `multiRelease = true` executes `jdeps --multi-release base ....`

I think it makes sense to leave the `multiRelease` option, but I'd like to find a way to automatically set the value to `true` if we detect that the uberjar is a multi-release jar
