### ISSUE TITLE
Add full-support for runtime dependencies (mkCljBin/docker)

### ISSUE THREAD

**Issue by thenonameguy** [jlesquembre/clj-nix#22]
Let's say your project depends on shelling out to `graphviz`, it's not immediately obvious how to set this up using the current documentation.

The `@attrs` pattern of passing through to `mkDerivation` could work I guess for the `mkCljBin` usecase.
For the Docker case, since we are dropping the `bash` dependency, the only way would be to do explicit `PATH` management:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/docker/examples.nix#L192

Adding documentation for this would be great for newcomers as for non-trivial applications controlling the execution environment of the jar file is very important.

**Comment by jlesquembre** [comment]
I did some small changes and updated the README on #24. What do you think? If the docs look clear to you, I'll merge it
