### ISSUE TITLE
BUG: mkCljCli is broken

### ISSUE THREAD

**Issue by thenonameguy** [jlesquembre/clj-nix#23]
Steps to reproduce using the `clj-demo-project` :
```bash
$ git clone https://github.com/jlesquembre/clj-demo-project 
$ git rev-parse HEAD                                       
8da3f5cd9366c040773e0dc7a9df513431d16314
$ nix build .#clj-container                    
error: attribute 'classpath' missing

       at /nix/store/f1jwm51q45l4gg377yiki0yf18smnc5n-source/helpers.nix:27:14:

           26|           "-classpath"
           27|           "${jdkDrv.classpath}"
             |              ^
           28|           "clojure.main"
(use '--show-trace' to show detailed location information)
```
Checking out `48c04b5` is the last commit, that doesn't throw this error.

**Comment by thenonameguy** [comment]
Note: a `nix flake check` in CI would have caught this. This fails at the moment for both this repo and the `clj-demo-project`.

**Comment by jlesquembre** [comment]
Thanks for the report, I forgot to update the helper function, it was expecting the old `mkCljBin` derivation.

I like the `nix flake check` idea, but unfortunately currently it fails with this error: 

```
a 'aarch64-darwin' with features {} is required to build '/nix/store/...', but I am a 'x86_64-linux' with features {}
```

If I find a way to run the checks only on one architecture, while using all the architectures for the packages, I'll add a CI check
