### ISSUE TITLE
can this be used for application development?

### ISSUE THREAD

**Issue by drewverlee** [jlesquembre/clj-nix#29]
I'm trying to understand how I would use Nix and NixOs to setup an application development context to build clojure applications. The Derivations in the API section of the readme seem to talk in terms of producing clojure applications, but not developing them e.g loading up emacs, connecting to a repl, using chrome to search, etc... I assume all of that should be managed by NixOs the same way it's currently done on my OS (ubuntu). 

Wasn't sure where to ask questions of this nature, so i'm using a github issue. feel free to redirect and thanks for building this :)

**Comment by jlesquembre** [comment]
Hi, totally fine to ask here, but other platforms (like slack) are also ok

clj-nix is more focused on the building part, but I added some helpers you can use for development. 

The way I use Nix to develop clojure applications:
- Editor (emacs, neovim, ...) is provided by my OS (NixOS in my case)
- I have a flake.nix per project. There I define the exact clojure version I want to use, and define any other dependencies needed for that project, including development dependencies, like clojure-lsp, babashka or any helper scripts. Notice that the flake.nix is shared between project members with different OSs (ubuntu, macos, ...). I run `nix develop .` at the root of the project to enter a sub-shell where all the dev dependencies are available. (Well, I use [direnv](https://direnv.net/), I just need to `cd` to the project directory)

The part where clj-nix can help you during development is with custom babashka helper scripts. You can use the [bbTasksFromFile](https://github.com/jlesquembre/clj-nix#bbTasksFromFile) function to expose clojure functions as shell functions. (an execute those with babashka)

I hope that clarifies it a bit, feel free to ask anything unclear

**Comment by jlesquembre** [comment]
I'm closing it, but feel free to re-open it (or open a new one) if you have more questions.
