### ISSUE TITLE
wsl problem

### ISSUE THREAD

**Issue by PlumpMath** [jlesquembre/clj-nix#30]
It seems that the wsl nixos project is trying to use the windows native version of the jdk. (In my personal opinion, it's much better (because it's really convenient if you do nix to generate the clojure version binary that the company is using).
If I'm right,
For using openjdk (windows version) within wsl nixos.
stdenv.isWSL I wish there was a nix code like this.
I'll leave it on the wsl nixos side as well.
Thank you

        > checking openjdk-target os-cpu... windows-x86_64
        > checking compilation type... native
        > checking Windows environment type... wsl1
        > configure: error: Incorrect wsl1 installation. Neither cygpath nor wslpath was found
        > configure exiting with result code 1
        For full logs, run 'nix log /nix/store/44bc59k1kqlm1pda6487z3hfqykdmh58-openjdk-headless-17.0.4+8.drv'.
       error: 1 dependencies of derivation '/nix/store/lm896fjw58i62jx1jhs5jhp0pdhn7ym6-openjfx-modular-sdk-17.0.0.1+1.drv'    failed to build
       error: 1 dependencies of derivation '/nix/store/w6x1djjnabybmahfiq0jm89kpybvgi2j-openjdk-17.0.4+8.drv' failed to build
       error: 1 dependencies of derivation '/nix/store/wcqripmmcwjsm7zzg84xmfxrc0p56d9n-clj-nix-hello-DEV.drv' failed to build
       error: 1 dependencies of derivation '/nix/store/placxm6f8wg1bgmfi00lajyzni25k09p-clojure-1.11.1.1165.drv' failed to build
       error: 1 dependencies of derivation '/nix/store/6fw2msz60z5pzkf20rj3ccxdrj254h4i-system-path.drv' failed to build
       error: 1 dependencies of derivation '/nix/store/c6sld3scg6v18sx1lhsfmjxiqp0sr0sl-nixos-system-win11-22.11.20220920.171ed77.drv' failed to build

nix log /nix/store/44bc59k1kqlm1pda6487z3hfqykdmh58-openjdk-headless-17.0.4+8.drv

   1   │ @nix { "action": "setPhase", "phase": "unpackPhase" }
   2   │ unpacking sources
   3   │ unpacking source archive /nix/store/jnm5kz67z1hg15mj35p7vqlij67knl7h-source
   4   │ source root is source
   5   │ @nix { "action": "setPhase", "phase": "patchPhase" }
   6   │ patching sources
   7   │ applying patch /nix/store/881pcwinv35z9f6c5max2m7il0sxvg3n-fix-java-home-jdk10.patch
   8   │ patching file src/hotspot/os/linux/os_linux.cpp
   9   │ Hunk #1 succeeded at 2597 with fuzz 2 (offset 327 lines).
  10   │ applying patch /nix/store/3zfcang88j3y15viz1b4c83dwxpl9ps6-read-truststore-from-env-jdk10.patch
  11   │ patching file src/java.base/share/classes/sun/security/ssl/TrustStoreManager.java
  12   │ Hunk #1 succeeded at 69 (offset -2 lines).
  13   │ Hunk #2 succeeded at 132 (offset -1 lines).
  14   │ Hunk #3 succeeded at 145 (offset -1 lines).
  15   │ applying patch /nix/store/08307j5x1ip16s0b0nik01i77pz6zch1-currency-date-range-jdk10.patch
  16   │ patching file make/jdk/src/classes/build/tools/generatecurrencydata/GenerateCurrencyData.java
  17   │ Hunk #1 succeeded at 311 (offset 30 lines).
  18   │ applying patch /nix/store/5kqw0l5s940vbp7gxz59vk9fad25v3wr-increase-javadoc-heap-jdk13.patch
  19   │ patching file make/Docs.gmk
  20   │ Hunk #1 succeeded at 274 (offset -3 lines).
  21   │ applying patch /nix/store/5izfn84pl9bcja2h5gavl7pd9dx5izss-ignore-LegalNoticeFilePlugin-jdk17.patch
  22   │ patching file src/jdk.jlink/share/classes/jdk/tools/jlink/internal/plugins/LegalNoticeFilePlugin.java
  23   │ applying patch /nix/store/1nvjqngnpbyxvlvh7jm9rmn9v0yic7pz-fix-library-path-jdk17.patch
  24   │ patching file src/hotspot/os/linux/os_linux.cpp
  25   │ patch unexpectedly ends in middle of line
  26   │ Hunk #3 succeeded at 468 with fuzz 2.
  27   │ applying patch /nix/store/hq4y9kq66c7h6dhi7nb5vx2ibn6fcbd3-rh1673833-remove_removal_of_wformat_during_test_compilation.patch
  28   │ patching file make/common/TestFilesCompilation.gmk
  29   │ Hunk #1 succeeded at 99 with fuzz 1 (offset 2 lines).
  30   │ patching script interpreter paths in configure
  31   │ configure: interpreter directive changed from "#!/bin/bash" to "/nix/store/p7bpdnxqd3i5hwm92mrscf7mvxk66404-bash-5.1-p16/bin/bash"
  32   │ @nix { "action": "setPhase", "phase": "configurePhase" }
  33   │ configuring
  34   │ configure flags: --prefix=/nix/store/fng7y0s5gpr8rk6k5z0zdf378pjhf7yc-openjdk-headless-17.0.4+8 --bindir=/nix/store/fng7y0s5gpr8rk6k5z0zdf378pjhf7yc
       │ -openjdk-headless-17.0.4+8/bin --sbindir=/nix/store/fng7y0s5gpr8rk6k5z0zdf378pjhf7yc-openjdk-headless-17.0.4+8/sbin --includedir=/nix/store/fng7y0s5
       │ gpr8rk6k5z0zdf378pjhf7yc-openjdk-headless-17.0.4+8/include --oldincludedir=/nix/store/fng7y0s5gpr8rk6k5z0zdf378pjhf7yc-openjdk-headless-17.0.4+8/inc
       │ lude --mandir=/nix/store/fng7y0s5gpr8rk6k5z0zdf378pjhf7yc-openjdk-headless-17.0.4+8/share/man --infodir=/nix/store/fng7y0s5gpr8rk6k5z0zdf378pjhf7yc-
       │ openjdk-headless-17.0.4+8/share/info --docdir=/nix/store/fng7y0s5gpr8rk6k5z0zdf378pjhf7yc-openjdk-headless-17.0.4+8/share/doc/openjdk-headless --lib
       │ dir=/nix/store/fng7y0s5gpr8rk6k5z0zdf378pjhf7yc-openjdk-headless-17.0.4+8/lib --libexecdir=/nix/store/fng7y0s5gpr8rk6k5z0zdf378pjhf7yc-openjdk-headl
       │ ess-17.0.4+8/libexec --localedir=/nix/store/fng7y0s5gpr8rk6k5z0zdf378pjhf7yc-openjdk-headless-17.0.4+8/share/locale --with-boot-jdk=/nix/store/kyk4q
       │ 5n2aynqk04ykzxy3fdnj1djbmir-adoptopenjdk-hotspot-bin-17.0.2 --with-version-build=8 --with-version-opt=nixos --with-version-pre= --enable-unlimited-c
       │ rypto --with-native-debug-symbols=internal --with-libjpeg=system --with-giflib=system --with-libpng=system --with-zlib=system --with-lcms=system --w
       │ ith-stdc++lib=dynamic --with-jvm-features=zgc --enable-headless-only
  35   │ Runnable configure script is not present
  36   │ Generating runnable configure script at /build/source/build/.configure-support/generated-configure.sh
  37   │ Using autoconf at /nix/store/rsh5wlvqv4fvzl298j43nv9r0w375b52-autoconf-2.71/bin/autoconf [autoconf (GNU Autoconf) 2.71]
  38   │ stdin:227: warning: AC_CHECK_HEADERS($HEADERS_TO_CHECK): you should use literals
  39   │ ./lib/autoconf/headers.m4:217: AC_CHECK_HEADERS is expanded from...
  40   │ /build/source/make/autoconf/libraries.m4:95: LIB_SETUP_LIBRARIES is expanded from...
  41   │ stdin:227: the top level
  42   │ configure: Configuration created at Tue Sep 20 07:03:43 UTC 2022.
  43   │ checking for basename... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/basename
  44   │ checking for dirname... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/dirname
  45   │ checking for file... /nix/store/84li3np5vv3p5az96lxfgxm0xjadi5x7-file-5.42/bin/file
  46   │ checking for ldd... /nix/store/jqb18w342wz9sc9jlc8blq80ms44pak3-glibc-2.35-163-bin/bin/ldd
  47   │ checking for bash... /nix/store/p7bpdnxqd3i5hwm92mrscf7mvxk66404-bash-5.1-p16/bin/bash
  48   │ checking for cat... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/cat
  49   │ checking for chmod... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/chmod
  50   │ checking for cp... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/cp
  51   │ checking for cut... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/cut
  52   │ checking for date... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/date
  53   │ checking for gdiff... [not found]
  54   │ checking for diff... /nix/store/jay2imyql1mljkck4g3dnbnak6sd5ks6-diffutils-3.8/bin/diff
  55   │ checking for echo... echo [builtin]
  56   │ checking for expr... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/expr
  57   │ checking for find... /nix/store/k0kpf3r2k1d8p9h0gmx23msw3qrybkfk-findutils-4.9.0/bin/find
  58   │ checking for gunzip... /nix/store/nc3xqj1cq6h418qmqlha193mvmbhx4bp-gzip-1.12/bin/gunzip
  59   │ checking for pigz... [not found]
  60   │ checking for gzip... /nix/store/nc3xqj1cq6h418qmqlha193mvmbhx4bp-gzip-1.12/bin/gzip
  61   │ checking for head... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/head
  62   │ checking for ln... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/ln
  63   │ checking for ls... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/ls
  64   │ checking for gmkdir... [not found]
  65   │ checking for mkdir... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/mkdir
  66   │ checking for mktemp... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/mktemp
  67   │ checking for mv... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/mv
  68   │ checking for gawk... /nix/store/mdvw541sarkk8jxfrf9jyjz1gs46wyjn-gawk-5.1.1/bin/gawk
  69   │ checking for printf... printf [builtin]
  70   │ checking for rm... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/rm
  71   │ checking for rmdir... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/rmdir
  72   │ checking for sh... /nix/store/p7bpdnxqd3i5hwm92mrscf7mvxk66404-bash-5.1-p16/bin/sh
  73   │ checking for sort... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/sort
  74   │ checking for tail... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/tail
  75   │ checking for gtar... [not found]
  76   │ checking for tar... /nix/store/f4ja1s5wxs2fxvcyz6kaaqj75icjfrrm-gnutar-1.34/bin/tar
  77   │ checking for tee... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/tee
  78   │ checking for touch... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/touch
  79   │ checking for tr... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/tr
  80   │ checking for uname... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/uname
  81   │ checking for wc... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/wc
  82   │ checking for xargs... /nix/store/k0kpf3r2k1d8p9h0gmx23msw3qrybkfk-findutils-4.9.0/bin/xargs
  83   │ checking for grep that handles long lines and -e... /nix/store/ix6nn9lwp2w04agkfb1wzwvcnis0mmxw-gnugrep-3.7/bin/grep
  84   │ checking for egrep... /nix/store/ix6nn9lwp2w04agkfb1wzwvcnis0mmxw-gnugrep-3.7/bin/grep -E
  85   │ checking for fgrep... /nix/store/ix6nn9lwp2w04agkfb1wzwvcnis0mmxw-gnugrep-3.7/bin/grep -F
  86   │ checking for a sed that does not truncate output... /nix/store/5mgbisml783jj5mscxjsr4hlbmn25cyr-gnused-4.8/bin/sed
  87   │ checking for df... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/df
  88   │ checking for nice... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/nice
  89   │ checking for greadlink... [not found]
  90   │ checking for readlink... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/readlink
  91   │ checking for cygpath... [not found]
  92   │ checking for wslpath... [not found]
  93   │ checking for lsb_release... [not found]
  94   │ checking for cmd.exe... [not found]
  95   │ checking for cmp... /nix/store/jay2imyql1mljkck4g3dnbnak6sd5ks6-diffutils-3.8/bin/cmp
  96   │ checking for uniq... /nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/uniq
  97   │ checking build system type... x86_64-pc-wsl
  98   │ checking host system type... x86_64-pc-wsl
  99   │ checking target system type... x86_64-pc-wsl
 100   │ checking openjdk-build os-cpu... windows-x86_64
 101   │ checking openjdk-target os-cpu... windows-x86_64
 102   │ checking compilation type... native
 103   │ checking Windows environment type... wsl1
 104   │ configure: error: Incorrect wsl1 installation. Neither cygpath nor wslpath was found
 105   │ configure exiting with result code 1

**Comment by jlesquembre** [comment]
Not sure if there is anything I can do on clj-nix, looks like a problem on NixOS-WSL side

**Comment by PlumpMath** [comment]
(The problem was solved the day after I wrote this article.)
Also, I am not familiar with the above-mentioned wsl (window native jdk) problem.
There is a feeling that the platform is progressing,
If jdk is changed to windows native cmd jdk inside wsl, clj-nix doesn't matter, right?
