### ISSUE TITLE
Add check for :gen-class in main entry file

### ISSUE THREAD

**Issue by jlesquembre** [jlesquembre/clj-nix#35]

**Comment by slimslenderslacks** [comment]
I started working on a rewrite-clj check in #39

**Comment by slimslenderslacks** [comment]
@jlesquembre should we close this one now that #39 is merged?  I could make a note in the README.md to let people know that we are automatically doing this check on the main-class when running mkCljBin, and then close this issue.

**Comment by jlesquembre** [comment]
Yes, we should close this one, I forgot it.
A note in the README is a good idea, thanks. As you said, I'll wait until you add the note, and then I'll close it.

**Comment by jlesquembre** [comment]
@slimslenderslacks I added a note in the README: https://github.com/jlesquembre/clj-nix/commit/5361db227c9f6f8928a287f4faa5de84b833c81d

Closing it, but any suggestion about the documentation is very welcome.
