### ISSUE TITLE
Include/exclude deps.edn in patchPhase

### ISSUE THREAD

**Issue by Sohalt** [jlesquembre/clj-nix#78]
While it's already possible to include/exclude some `deps.edn` files in lockfile generation (using `--deps-include` and `--deps-exclude`), the `patch-git-sha` command during `patchPhase` tries to patch all `deps.edn` files. It would be nice to be able to granularly specify which files to patch (or record which files where included/excluded in the lockfile and have the patch phase automatically pick that up).

**Comment by jlesquembre** [comment]
Good catch. I think in that case makes more sense to simple ignore those dependencies.

 `patch-git-sha` should expand only the `sha`s in the lock file, ignoring the others (instead of failing). Makes sense? I don't think we need to save the included/excluded files in the lock file.

**Comment by Sohalt** [comment]
We should be able to deal with files called `deps.edn` that are not valid edn.

**Comment by jlesquembre** [comment]
What's the use case to deal with deps.edn files that aren't valid edn?

**Comment by Sohalt** [comment]
I have a `deps.edn` with `{{}}` placeholders for use with deps-new templating.

**Comment by jlesquembre** [comment]
@Sohalt could you try #80?

**Comment by Sohalt** [comment]
Thank you! And sorry for not getting back on this earlier. I just tried it and it works as expected!

**Comment by jlesquembre** [comment]
@Sohalt no worries, thanks for testing it!
