### ISSUE TITLE
Add support for tracking POMs (so we can build local Maven caches)

### ISSUE THREAD

**Issue by charles-dyfis-net** [jlesquembre/clj-nix#8]
Right now, clj-nix can create a classpath with everything needed to build and run a given application.

That works for projects for which it's sufficient; however, some larger projects may have existing build stacks they're already happy with, but want to be able to use from inside a sandboxed Nix builder.

Adding a URL and hash for the POM associated with each dependency should be sufficient to permit a clj-nix target that creates a local Maven repository that build tools can use unmodified.

Consider this ticket a request for feedback on whether such a charge would be welcome.

**Comment by jlesquembre** [comment]
Your goal is to create a local maven cache, to be able to run clj build tools during nix build phase. Right?

**Comment by charles-dyfis-net** [comment]
> Your goal is to create a local maven cache, to be able to run clj build tools during nix build phase. Right?

Right.

**Comment by jlesquembre** [comment]
I'm working on the next clj-nix iteration, which should make it easier to expose the maven cache to the nix builder. I'll keep you posted.

**Comment by jlesquembre** [comment]
I added a new function, `mk-deps-cache`: https://github.com/jlesquembre/clj-nix/blob/20171ecae3e81568918bb89b87f90c4f66f67e9c/flake.nix#L32

It's called internally by `mkCljBin`: https://github.com/jlesquembre/clj-nix/blob/20171ecae3e81568918bb89b87f90c4f66f67e9c/pkgs/mkCljBin.nix#L44-L47

You could use it to create a local maven + gitdeps cache.

Notice that now `mkCljBin` accept a new argument, `buildCommand`, to execute any arbitrary clj command (e.g.: `clj -T:build`), which could be more convenient.

**Comment by jlesquembre** [comment]
Added some docs here:
https://github.com/jlesquembre/clj-nix#mk-deps-cache

Open a new ticket if you find any issues or something in unclear
