### ISSUE TITLE
BUG: customJdk ignores java-opts

### ISSUE THREAD

**Issue by uvNikita** [jlesquembre/clj-nix#92]
In the current implementation, binary script produced by `customJdk` ignores specified `java-opts`.

I think the culprit is `binaryTemplate` used in `cljHooks.nix` which ignores `java-opts`:

https://github.com/jlesquembre/clj-nix/blob/52e174b2fc7805bc5a6b100d5ed7052e172a1bf2/pkgs/cljHooks.nix#L18-L23

Removing `customJdk.enable = true` fixes the issue but produces unoptimized JDK.

**Comment by jlesquembre** [comment]
Thanks for reporting, this PR should fix it: #93 

You can test it by updating your nix flake input:

```nix
clj-nix.url = "github:jlesquembre/clj-nix/fix/customJdk-java-opts";
```
